[nfs]
172.31.36.99 ansible_ssh_user=ec2-user

[webservers]
172.31.36.90 ansible_ssh_user=ec2-user
172.31.47.217 ansible_ssh_user=ec2-user

[db]
172.31.36.136 ansible_ssh_user=ubuntu

[lb]
172.31.16.253 ansible_ssh_user=ubuntu
